[package]
name = "chemgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
wgpu = { workspace = true }
futures = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
thiserror = { workspace = true }
env_logger = { workspace = true }

# chemfp = { workspace = true }
chemcore = { workspace = true }

