[workspace]
members = ["chemcore", "chemfp", "chemgpu", "chemio"]

[workspace.dependencies]
nom  = "8.0.0" # Build safe Parsers
rayon = "1.11.0"
anyhow = "1.0"
thiserror = "2.0.17"

chemio = { path = "./chemio" }
chemfp = { path = "./chemfp" }
chemgpu = { path = "./chemgpu" }
chemcore = { path = "./chemcore" }

