[workspace]
members = ["chemcore", "chemfp", "chemgpu", "chemio"]

[workspace.dependencies]
log = "0.4.0"
nom  = "8.0.0" # Build safe Parsers
wgpu = "27.0.1"
rayon = "1.11.0"
anyhow = "1.0"
futures = "0.3.31"
pollster = "0.4.0"
bytemuck = { version = "1.24", features = ["derive"] }
thiserror = "2.0.17"
env_logger = "0.11.8"

chemio = { path = "./chemio" }
chemfp = { path = "./chemfp" }
chemgpu = { path = "./chemgpu" }
chemcore = { path = "./chemcore" }

