//! Residue and chain topology, for the formats that are organised by it.

use std::fmt;
use std::ops::Range;

/// One chain, and the residues it owns.
///
/// Held on [`Molecule`] alongside the residues rather than as a per-atom
/// column: a chain is a grouping, and the atoms it covers are reachable
/// through its residues.
///
/// [`Molecule`]: crate::core::molecule::Molecule
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Chain {
    /// Identifier as written — `A`, `B`. A `String` rather than a `char`
    /// because mmCIF is not limited to a single character.
    ///
    /// This is the *depositor's* identifier (`auth_asym_id` in mmCIF), which is
    /// what a PDB file carries and what every paper and binding-site table
    /// refers to.
    pub id: String,

    /// The mmCIF canonical `label_asym_id`, when the source carried one.
    ///
    /// mmCIF numbers everything twice: `label_*` is regenerated by the
    /// deposition pipeline, `auth_*` is what the depositor used, and they
    /// frequently disagree. Neither is derivable from the other, so both are
    /// kept — reading one and writing the other silently renumbers a structure.
    pub label_id: Option<String>,

    /// Residues in this chain, as a range into [`Molecule::residues`].
    ///
    /// [`Molecule::residues`]: crate::core::molecule::Molecule::residues
    pub residues: Range<usize>,
}

/// One residue, and the atoms it owns.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Residue {
    /// Three-letter code or ligand name as written — `LYS`, `HOH`, `LIG`.
    pub name: String,

    /// Depositor numbering (`auth_seq_id`).
    ///
    /// Signed, because residue numbers genuinely go negative — an expression
    /// tag before the construct's first residue is conventionally numbered
    /// backwards from zero. It also repeats across chains, which is why
    /// identity is the (chain, sequence, insertion code) triple and never the
    /// number alone.
    pub sequence: i32,

    /// Insertion code. `58`, `58A` and `58B` are three distinct residues, all
    /// with `sequence` 58.
    pub insertion_code: Option<char>,

    /// The mmCIF canonical `label_seq_id`, when the source carried one.
    ///
    /// `None` for non-polymer residues — mmCIF itself writes `.` here for
    /// waters and ligands, so absent is a real answer rather than missing data.
    pub label_seq: Option<i32>,

    /// Index into [`Molecule::chains`].
    ///
    /// [`Molecule::chains`]: crate::core::molecule::Molecule::chains
    pub chain_ix: usize,

    /// `HETATM` rather than `ATOM` — a water, a ligand, an ion.
    ///
    /// Recorded on the way in because it is free here and expensive to
    /// reconstruct later: it is what a "strip solvent" or "extract ligand"
    /// operation keys on, and guessing it back from the residue name means
    /// carrying a list of every standard residue.
    pub is_hetero: bool,

    /// Atoms in this residue, as a range into the molecule's atoms.
    ///
    /// A range rather than a per-atom index because PDB and mmCIF already order
    /// their records this way, and it costs nothing per atom. The price is that
    /// a residue's atoms **must** be contiguous — an interleaved file is
    /// rejected rather than represented.
    pub atoms: Range<usize>,
}

impl Residue {
    /// Whether this residue covers `atom_idx`.
    pub fn contains_atom(&self, atom_idx: usize) -> bool {
        self.atoms.contains(&atom_idx)
    }

    /// How many atoms this residue owns.
    pub fn num_atoms(&self) -> usize {
        self.atoms.len()
    }
}

impl fmt::Display for Residue {
    /// `LYS 58`, or `LYS 58A` where an insertion code distinguishes it.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} {}", self.name, self.sequence)?;
        if let Some(code) = self.insertion_code {
            write!(f, "{code}")?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn residue(name: &str, sequence: i32, atoms: Range<usize>) -> Residue {
        Residue {
            name: name.to_string(),
            sequence,
            insertion_code: None,
            label_seq: None,
            chain_ix: 0,
            is_hetero: false,
            atoms,
        }
    }

    #[test]
    fn test_display_includes_an_insertion_code_only_when_there_is_one() {
        let plain = residue("LYS", 58, 0..9);
        assert_eq!(plain.to_string(), "LYS 58");

        let inserted = Residue {
            insertion_code: Some('A'),
            ..residue("LYS", 58, 9..18)
        };
        assert_eq!(inserted.to_string(), "LYS 58A");
    }

    #[test]
    fn test_a_negative_sequence_number_is_representable() {
        // Expression tags before the construct's first residue are numbered
        // backwards from zero, so an unsigned type would reject real files.
        let tag = residue("MET", -3, 0..8);
        assert_eq!(tag.to_string(), "MET -3");
    }

    #[test]
    fn test_atom_membership_comes_from_the_range() {
        let res = residue("GLY", 1, 4..7);
        assert_eq!(res.num_atoms(), 3);
        assert!(!res.contains_atom(3));
        assert!(res.contains_atom(4));
        assert!(res.contains_atom(6));
        assert!(!res.contains_atom(7));
    }
}
