[package]
name = "chemfp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[[bin]]
name = "hash_test"
path = "src/bin/hash_test.rs"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"

[dependencies]
bitvec = "1.0.1"
fxhash = "0.2.1"
rayon = { workspace = true }
thiserror = { workspace = true }

chemio = { workspace = true }
chemgpu = { workspace = true }
chemcore = { workspace = true }
